# Generated by Django 4.1.2 on 2022-11-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='info@unikmsg.com', max_length=200),
        ),
    ]
